### ISSUE TITLE
Model loading for each request in QuaggaServer

### ISSUE THREAD

**Issue by TimRepke** [HPI-Information-Systems/QuaggaLib#1]
Lädt der hier jedes Mal das ganze Modell neu von der Platte bei einer Anfrage? Das wäre ja dann ganz schön langsam.
So weit ich weiß vergisst Flask nach einer Weile ein geladenes Modell, aber dann sollte das lieber on demand aufgefrischt, aber dann vorgehalten werden.

https://github.com/HPI-Information-Systems/QuaggaLib/blob/99be59a61e1f7d51d0281383ccc1969bd8c47c3f/QuaggaServer/QuaggaServer.py#L23

Kontext:
```python
def five():
    data = request.get_json()
    model_builder = ModelBuilder(with_crf=(data.get('model', '') == 'crf'), zones=5, trainset=data.get('trainedOn', 'enron'))
    #quagga = Quagga(ListReaderExtractedBodies(data['rawText']), model_builder=model_builder)
    quagga._build_model(model_builder)
    prediction = quagga._predict(data.get('rawText'))
    return jsonify(prediction)
```

**Comment by ben243871694** [comment]
implemented simple cache
